### ISSUE TITLE
Survival Exploit fixes auflisten, damit Spieler wissen, was nicht geht

### ISSUE THREAD

**Issue by Abwasserrohr** [Abwasserrohr/SR-DOCS#19]
```
ConfigVersion: '2.0'
Exploits:
  Minecart:
    AlsoPreventHeadInside:
    - COMPOSTER
  RNGEnchant:
    PreventRNGEnchant: true
  DropperDupe:
    BlockLoopedDroppers: false
  FishMod:
    MaxFishAllowedBeforeKick: 5
    MaxFishToNotifyStaffThenBlock: 5
    WarnPlayerThenKickInsteadOfNotify: false
    WatchForAutoFishMod: true
  Nether:
    EnsureSafeTeleportLocationIfAboveCeiling: true
    BlockPlayersAboveNether: false
    NetherYLevel: 128
    KillPlayersBelowNether: false
    BlockBuildingAboveNether: false
    ExcludeNetherWorldFromHeightCheck: []
  OverStack:
    StackWhiteListMode: true
    AllowStack:
    - POTION
    PreventOverStackedItemInHoppers: true
    GroupStack: []
    RemoveOverstackedItems: true
    FixOverstackedItemInstead: false
    RemoveItemsOfType: []
  NetherPortal:
    PreventPortalTrap: true
  1_14_Exploits:
    Traders:
      VillagerRestockTime: 10
      BlockVillagerTradeCheesing: true
      ZombieVillagerTransformChance: 65
  Other:
    PreventCommandsInBed: true
    PreventItemSwapLagExploit: true
    PreventHoppersToUnloadedChunks: true
    DisableChestsOnMobs: true
    PreventBedrockDestruction: true
    PunishForChestsOnMobs: false
    PreventMinecartsInBoats: true
    PreventBedExplosions: true
    PreventRailDupe: true
    DisableRidingExploitableMobs: true
    PreventEndPortalDestruction: true
    PreventNestedShulkers: true
    PreventInvalidPotions: true
  PortalDupe:
    EndWhiteListMode: true
    BlockNonPlayersInEndPortal: true
    EndWhiteList: []
    NetherWhiteList: []
    NotifyBlockedPortalAttempts: false
    BlockNonPlayersInNetherPortal: true
    NetherWhiteListMode: true
  LavaDupe:
    PreventLavaDupe: true
  3rdParty:
    BlockCMIShulkerStacking: true
  Enchants:
    FixIllegalEnchants: false
    OnlyFunctionInWorlds: []
    DestroyIllegallyEnchantedItemsInstead: false
    AllowBypass: false
    RemoveCustomAttributes: false
    RemoveUnbreakableFlag: false
    CustomEnchantOverride: []
    EnchantedItemWhitelist: []
  1_15_Exploits:
    Dupes:
      PreventTripwireDupe: true
  SignExploit:
    DestroyBadSignsOnChunkLoad: false
  Teleport:
    PearlPhasing: true
  MineCart:
    PreventHeadInsideBlocks: false
    MinecartBlockWhiteList: []
    RemoveExistingGlitchedMinecarts: false
    PreventMinecartGlitch: true
  RecordDupe: true
  TNTDupe:
    PreventIndirectTNTPowerDupe: true
  EndGateway:
    PreventEndGatewayCrashExploit: true
  NegativeDurability: true
  Fishing:
    KickForAutoClickerFishing: true
  Looting:
    PreventLootingExploit: true
  BookExploit:
    DisableBookWriting: false
UserRequested:
  ItemRemoval:
    ItemLoresToRemove: []
    BlockRepairsInstead: false
    NameLoreStrictMatchMode: false
    BlockEnchantingInstead: false
    RemoveItemsMatchingName: false
    ItemNamesToRemove: []
  Misc:
    NotifyInsteadOfBlock: []
  NetherDamage:
    DamageAmount: 2
    DamagePlayersAboveNether: false
    DamageDelay: 2
  Obsure:
    Misc:
      RemoveAllRenamedItems: false
  Obscure:
    HopperCheck:
      IgnoreAllHopperChecks: false
    HackedShulker:
      DestroyInvalidShulkers: false
      CheckGroundForBadShulkerAtLogin: false
    IgnoreAllShulkerPlaceChecks: false
    BlockBadItemsFromCreativeTab: false
  Mobs:
    PreventZombieItemPickup: false
  Cobble:
    PreventCobbleGenerators: false
Misc:
  BreakMachinesInsteadOfDroppingItems: true
  ItemScanTimer: 10
  DisableInWorlds: []
  LogOffensesInSeparateFile: true
  NotifyNearbyPlayers: false
  Spawners:
    PreventSpawnEggsOnSpawners: true
  InGameOffenseNotifications: true
Exploit:
  LagMachines:
    ArmorStand: true
    End Crystal: true
  Teleport:
    CorrectionNotify: false
```
